FROM cyberdojofoundation/javascript-node:688a241
LABEL maintainer=jon@jaggersoft.com

WORKDIR /usr/local/lib/node_modules
RUN npm install jsdom
RUN npm install jquery
ENV NODE_PATH /usr/local/lib/node_modules

COPY red_amber_green.rb /usr/local/bin
