FROM cyberdojofoundation/javascript-node_assert
LABEL maintainer=jon@jaggersoft.com

WORKDIR /usr/local/lib/node_modules
RUN npm install jsdom
RUN npm install jquery
ENV NODE_PATH /usr/local/lib/node_modules
